<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Areas\**" />
    <Content Remove="Areas\**" />
    <EmbeddedResource Remove="Areas\**" />
    <None Remove="Areas\**" />
  </ItemGroup>
	<ItemGroup>
		<None Update="firebase-service-account.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
  <ItemGroup>
    <Folder Include="Data\Configurations\" />
    <Folder Include="Data\Migrations\" />
    <Folder Include="Views\Blogs\" />
    <Folder Include="Views\Posts\" />
    <Folder Include="Views\Admin\" />
    <Folder Include="Interfaces\" />
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="Google.Cloud.Firestore" Version="3.*" />

  </ItemGroup>

</Project>
